### ISSUE TITLE
在线观看视频可以支持外挂字幕吗？

### ISSUE THREAD

**Issue by WHYEX3** [liupan1890/aliyunpan#106]
在线观看视频可以支持外挂字幕吗？

**Comment by liupan1890** [comment]
直接把你的字幕文件，拖放到MPV正在播放的窗口上即可

**Comment by xioFelix** [comment]
我还特意把字幕合并上去重新上传了😂 这功能不错

**Comment by omy2000** [comment]
原来如此，厉害了大佬

**Comment by Kookoomoo** [comment]
@liupan1890 如果字幕和视频文件都在网络文件夹里，如何加载字幕呢？必须要下载下来吗？

**Comment by WHYEX3** [comment]
> @liupan1890 如果字幕和视频文件都在网络文件夹里，如何加载字幕呢？必须要下载下来吗？

是这样的

**Comment by zzxnmq** [comment]
> 
我也想问这个问题，自定义播放器的时候怎么外挂网盘的字母呢

**Comment by snow212-cn** [comment]
这就差劲了，人家阿里云盘tv版都支持外挂网盘字幕，你一个pc客户端还不支持

**Comment by JH2002YANA** [comment]
> 这就差劲了，人家阿里云盘tv版都支持外挂网盘字幕，你一个pc端还不支持
下载下来拖进去就行了，字幕文件又不大，而且这个版本比官方PC端好用多了

**Comment by chengnan049** [comment]
> 这就差劲了，人家阿里云盘tv版都支持外挂网盘字幕，你一个pc端还不支持

TV和PC又不是一个开发者，没人逼着你用，播放器调用的是MPV支持外挂字幕，是你不会用，外挂字幕需要拖动进去，你要是想让项目更好用应该提交PR

**Comment by zzxnmq** [comment]
> > 这就差劲了，人家阿里云盘tv版都支持外挂网盘字幕，你一个pc端还不支持
> 
> TV和PC又不是一个开发者，没人逼着你用，播放器调用的是MPV支持外挂字幕，是你不会用，外挂字幕需要拖动进去，你要是想让项目更好用应该提交PR

太奇怪了，为什么这条回复会给我发邮箱提醒啊，我还以为是怼我的QAQ

**Comment by chengnan049** [comment]
> > > 这就差劲了，人家阿里云盘tv版都支持外挂网盘字幕，你一个pc端还不支持
> > 
> > 
> > TV和PC又不是一个开发者，没人逼着你用，播放器调用的是MPV支持外挂字幕，是你不会用，外挂字幕需要拖动进去，你要是想让项目更好用应该提交PR
> 
> 太奇怪了，为什么这条回复会给我发邮箱提醒啊，我还以为是怼我的QAQ

回复这条 Issue 就会 Subscribe 通知，可以点 Unsubscribe 取消掉

**Comment by zzxnmq** [comment]
> 

好的谢谢大佬

**Comment by C-CYoung** [comment]
播放视频时报错errorHandler //== Error ==// Cannot set properties of undefined (setting 'default') //== Stack ===// TypeError: Cannot set properties of undefined (setting 'default') at ie (file:///G:/alixby/resources/app.asar/dist/index.js:283:54113) at async file:///G:/alixby/resources/app.asar/dist/index.js:283:50489
