### ISSUE TITLE
linux下使用有问题，提示aria2本地连接已断开

### ISSUE THREAD

**Issue by xiayuxingtian** [liupan1890/aliyunpan#474]
Uncaught Error: Unhandled error. (undefined)
onerror
Error: Unhandled error. (undefined) at o.c.emit (file://***/electron/resources/app.asar/dist/renderer/umi.js:1:43779) at WebSocket.e.onerror (file:///***/electron/resources/app.asar/dist/renderer/umi.js:1:80068)
Unhandled error. (undefined)
Uncaught Error: Unhandled error. (undefined)

**Comment by liupan1890** [comment]
>file:///electron/resources/app.asar/dist/renderer/umi.js:1:43779

错误原因

第一可能是“electron\resources\aria2c”没能正确的启动，这个原因比较多，不知道你具体是哪个原因



第二可能是你是用代理切换代理/网卡导致的临时性故障，重启小白羊一般可以恢复


---

其实小白羊在linux下用户也不少，大部分人可以双击后正常运行，确实会有少部分人遇到无法正常运行，但这个并不是小白羊有BUG，也跟用户的环境有关系（linux 是什么系统/版本/安装了哪些依赖/什么CPU/32-64位）
所以当你之说遇到aria2本地连接已断开，我知道是因为aria2c没能正确链接，但我也不知道为什么，需要你详细的描述您的具体情况，才能依此推断原因

**Comment by Jontyshaw** [comment]
我的在升级2.12.05后也有这问题，但是不升级一切都正常，先继续用2.11吧

**Comment by Jontyshaw** [comment]
> 应该是aria2c崩溃了，简单的方法就是用你系统的aria2c替换resource下的二进制文件。 你仔细看看system log，dmesg之类的，会发现aria2c其实是段错误了。

是这样的，刚刚我试了，复制系统的aria2c文件，可以下载了

**Comment by Ssiswent** [comment]
> 

请问具体是替换哪里的文件呢，系统的aria2c文件又是在哪里提取呢，谢谢

**Comment by alex14563** [comment]
啥时候出新版本解决这个呢？
