### ISSUE TITLE
设置系统自带的aria2c程序(Linux)

### ISSUE THREAD

**Issue by GraphGuru** [liupan1890/aliyunpan#506]
Hi, Guys!

  目前在resource里面自带aria2c程序，但是我的系统可能libc比较新（archlinux），这个aria2c在执行过程中在libc中崩溃了。
程序是不是可以增加一个配置使用系统的aria2c的选项？或者已经有了？

**Comment by liupan1890** [comment]
resource里面自带的aria2c程序，你可以直接使用自己的版本替换掉

你可以从aria的官方github或者其他作者的修改版本里，下载到适合你系统/平台的aria2c文件，直接替换即可正常使用

**Comment by dickwu** [comment]
我这边使用的的Mac m1 的 aria2 version 1.36.0 替换后 本地服务无法启动
 Error: Unhandled error. (undefined) at o.c.emit (file:///Applications/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98%E5%B0%8F%E7%99%BD%E7%BE%8A%E7%89%88v2.app/Contents/Resources/app.asar/dist/renderer/umi.js:1:43779) at WebSocket.e.onerror (file:///Applications/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98%E5%B0%8F%E7%99%BD%E7%BE%8A%E7%89%88v2.app/Contents/Resources/app.asar/dist/renderer/umi.js:1:80068)

**Comment by liupan1890** [comment]
试一下这个：

https://github.com/RobotsAndPencils/XcodesApp/blob/350e5708b7da6bab51ada79bdc829585bd804112/Xcodes/Resources/aria2c-arm64

注意：
小白羊mac版，内置的aria2c是aria2官方发布的的1.35版本。aria2官方并未发布aria2的1.36 mac编译版本
所以，你提到**Mac m1 的 aria2 version 1.36.0 替换后 本地服务无法启动** 可能是因为版本不适合mac--瞎猜的

仅针对阿里云盘下载这个场景，aria2 v1.35 和v1.36使用上并没啥差别，所以其实也不需要更换最新的v1.36

**Comment by dickwu** [comment]
我是使用的 brew 下载的，把包的 config 文件拷贝出来后用 terminal 启动后也可以用，就是覆盖进去时启动会有问题

**Comment by GraphGuru** [comment]
> resource里面自带的aria2c程序，你可以直接使用自己的版本替换掉
> 
> 你可以从aria的官方github或者其他作者的修改版本里，下载到适合你系统/平台的aria2c文件，直接替换即可正常使用
> 
> > 增加一个配置使用系统的aria2c的选项
> 
> 不需要，直接覆盖替换文件即可

目前就是用系统的替换resource下的文件，但是觉得这样有一些hack around，用这种逻辑怎么样： 对于Linux系统来说，如果系统的PATH中有aria2c，并且version合适，就用系统的aria2c，如果没有才用resource里面自带的？

**Comment by dickwu** [comment]
> > resource里面自带的aria2c程序，你可以直接使用自己的版本替换掉
> > 你可以从aria的官方github或者其他作者的修改版本里，下载到适合你系统/平台的aria2c文件，直接替换即可正常使用
> > > 增加一个配置使用系统的aria2c的选项
> > 
> > 
> > 不需要，直接覆盖替换文件即可
> 
> 目前就是用系统的替换resource下的文件，但是觉得这样有一些hack around，用这种逻辑怎么样： 对于Linux系统来说，如果系统的PATH中有aria2c，并且version合适，就用系统的aria2c，如果没有才用resource里面自带的？

这种蛮好的
