### ISSUE TITLE
v2和v3支持苹果m1/m2吗？

### ISSUE THREAD

**Issue by CrazyJasonwell** [liupan1890/aliyunpan#897]
v2在m1下不能工作

**Comment by pongfcnkl** [comment]
用这个
https://github.com/missuo/AliyunPanMac/releases

**Comment by CrazyJasonwell** [comment]
能登录进app，但是报错，这些错不能关闭，点击也没用
<img width="998" alt="报错" src="https://user-images.githubusercontent.com/109327188/222667404-fce0aaaa-1c13-4d17-bedc-2223d093019e.png">

**Comment by CrazyJasonwell** [comment]
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at oe.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:52799) at ue.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60620)
Uncaught Error: Unhandled error. (undefined)

运行日志见上。
onerror
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at oe.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:52799) at ue.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60620)
Uncaught Error: Unhandled error. (undefined)
onerror
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at oe.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:52799) at ue.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60620)
Uncaught Error: Unhandled error. (undefined)
onerror
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at oe.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:52799) at ue.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60620)
Uncaught Error: Unhandled error. (undefined)
onerror
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at oe.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:52799) at ue.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60620)
Uncaught Error: Unhandled error. (undefined)
onerror
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at oe.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:52799) at ue.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60620)
Uncaught Error: Unhandled error. (undefined)
onerror
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at oe.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:52799) at ue.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60620)
Uncaught Error: Unhandled error. (undefined)
onerror
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at oe.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:52799) at ue.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60620)
Uncaught Error: Unhandled error. (undefined)
onerror
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at oe.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:52799) at ue.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60620)
Uncaught Error: Unhandled error. (undefined)
onerror
onerror //== Error ==// Unhandled error. (undefined) //== Stack ===// Error: Unhandled error. (undefined) at oe.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:52799) at ue.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60620)
Uncaught Error: Unhandled error. (undefined)
onerror

**Comment by pongfcnkl** [comment]
自己另外运行个arai2，然后设置里切一下远程aria2
https://github.com/missuo/AliyunPanMac/blob/1c61b252ea929306a2e951395de60dd0996b7ad9/README.md
