### ISSUE TITLE
在线播放报错

### ISSUE THREAD

**Issue by C-CYoung** [liupan1890/aliyunpan#933]
在线播放时报错errorHandler //== Error ==// Cannot set properties of undefined (setting 'default') //== Stack ===// TypeError: Cannot set properties of undefined (setting 'default') at ie (file:///G:/alixby/resources/app.asar/dist/index.js:283:54113) at async file:///G:/alixby/resources/app.asar/dist/index.js:283:50489

**Comment by C-CYoung** [comment]
我记得是可以直接删除哪个文件来着,忘记了
